### ISSUE TITLE
Move from procedural to object

### ISSUE THREAD

**Issue by glonlas** [gcarq/freqtrade#492]
This request is to move the bot from a procedural code with static functions and duplicated code to a modulable object bot.

## Which file will be updated?
Here the list of file I target to migrate slowly to classes:
- [x] `main.py` -> into different classes, splitting trading logic / bot loop / configuration / RPC / Logging
- [x] `misc.py` -> into a configuration class that can be reuse for every script (Backtesting, Hyperopt, plots, ...)
- [x] `analyze.py` -> into a analyse/trading class (will integrate some logic that is today inside main.py)
- [x] `rpc/init.py` -> into a RPC class
- [x] `rpc/telegram.py` -> into a RPC plugin: Telegram
- [x] `optimize/backtesting.py` -> into a Backtesting class
- [x] `optimize/hyperopt.py` -> into a Hyperopt class
- [x] Update plot scripts

## Why?
We see at many places in the bot logic that is duplicated and sometimes not updated at the same time. We have even more bugs due to duplicated code. By moving to modular classes we ensure the bot will use the exact same logic all the time.

## How do you know you are not missing to port functions or not changing current behavior?
First, unittest are mandatory. The new code must have 95% of code coverage, and moreover, it must reuse the existing unittests.

Second, the bot has static functions, when a function is not ported to a class; the bot will continue to call it.

Third, move static function into methods (remove the previous function) to ensure the logic exist at only one place and does not have duplicate.

**Comment by glonlas** [comment]
## Current Development Status
To provide an update. By Monday we should have a refactored branch online. 
- Main code was cleaned up, and reduce to bot execution logic only.
- Bot logic has move in a class called `Freqtradebot()`
- Trading/Ticker analysis logic contained in `main.py` , `__init__.py`, `misc.py` has been consolidated in a class `Analyze()`
- Argument parsing contained in misc.py have been changed to a class `Argument()`
- Configuration handling/parsing contained everywhere in `main.py`, and other files have been consolidated into a class `Configuration()`
- Backtesting is now an object as well `Backtesting()`
- RPC / Telegram, have moved to class as well, but are still coupled to the bot

Of course, unit tests have been added for any new class and method. Existing unit test are still present and passing.

## Todo
- Clean up hyperopt file, Move hyperopt logic to an object model and to use Backtesting class
- Update plot_scripts
- Rebase develop

## Will be unchanged
- Echange file and Bittrex class. I try to not disrupt CCXT/Binance WIP.

**Comment by glonlas** [comment]
Few updates about Backtesting performance. 
**Note:** This refactoring does not apply yet the incredible optimization of @vertti. So please do not be surprised to see high backtesting duration below.

To understand if the refactoring will improve the bot, I have tested the duration of the backtesting and memory usage before and after refactoring. 

- [x] Backtesting result: Same before and after (no regression)
- [x] Total backtesting duration reduced by 1sec (average on 10 identicals tests for both Before and After refactoring)
- [x] Memory usage reduced by 94MiB (average on 10 identicals tests for both Before and After refactoring)

**Comment by glonlas** [comment]
Update after a long wait. The branch [feature/objectify](https://github.com/gcarq/freqtrade/tree/feature/objectify) was pushed. 

If the bot code has changed, I did my best to not change the logic and keep all unit tests. I have not changed the logic of the unit tests to reduce/avoid the feature regression.

## Tested in Dry-run
This branch has been tested in Dry-run only. Please DO NOT USE it for prod. Lot of work is still required. But feel free to test it and send your comments.

## Breaking changes
As you will see most of the bot is now using classes and objects. This refactor is huge and will impact all PR developed on the master|develop branch.
## Outdated
Because the development was long, this branch is outdated compared to `develop`. I did not have the chance to port all the PR merged since the last 3 weeks. This is part of the next step.

## Next step
- Porting all code changes merged since the last 3 weeks
- Asking help on Code review. It will be great if you could have a look at this refactor and send your feedbacks
- Make sure all unittest pass and more important no regression was introduced
- Test it, test it, test it

**Comment by shusso** [comment]
Closing as #537 was merged. Good stuff @glonlas 👍
